# Generated by Django 5.2 on 2025-04-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(unique=True)),
                ('title', models.CharField(default='', max_length=256)),
                ('editionNo', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
