# Generated by Django 5.2 on 2025-04-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(db_column='EID', primary_key=True, serialize=False)),
                ('fname', models.CharField(db_column='Fname', max_length=50)),
                ('lname', models.CharField(db_column='Lname', max_length=50)),
                ('salary', models.IntegerField(db_column='Salary', null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(db_column='sname', max_length=50)),
            ],
            options={
                'db_table': 'specialization',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Requires',
        ),
        migrations.DeleteModel(
            name='SupportStaff',
        ),
        migrations.DeleteModel(
            name='WorksFor',
        ),
    ]
